nodeLinker: pnp
pnpMode: loose
yarnPath: .yarn/releases/yarn-4.1.0.cjs

packageExtensions:
  "prettier@*":
    dependencies:
      "@babel/parser": "*"
      "@babel/core": "*"
  "stylelint-order@*":
    dependencies:
      "postcss": "*"
      "postcss-scss": "*"
  "stylelint@*":
    dependencies:
      "postcss": "*"
      "postcss-scss": "*"
  "stylelint-prettier@*":
    dependencies:
      "prettier-linter-helpers": "*"
