export { default as IcHamburgar } from "./IcHamburgar";
export { default as IconArrowLeft } from "./IconArrowLeft";
export { default as IconArrowRight } from "./IconArrowRight";
export { default as IconCheck } from "./IconCheck";
export { default as IconLogo } from "./IconLogo";
export { default as IconMinus } from "./IconMinus";
export { default as IconPlus } from "./IconPlus";
export { default as IconTextfiedlDelete } from "./IconTextfiedlDelete";
export { default as IconXButton } from "./IconXButton";
