export const dummyData = {
  promotionList: [
    {
      promotionId: 1,
      promotionPhoto: "홍보이미지 URL",
      performanceId: 1,
    },
    {
      promotionId: 2,
      promotionPhoto: "홍보이미지2 URL",
      performanceId: 2,
    },
  ],
  performanceList: [
    {
      performanceId: 1,
      performanceTitle: "새소년 밴드",
      performancePeriod: "2023.12.28",
      ticketPrice: 5000,
      dueDate: 1,
      genre: "BAND",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 2,
      performanceTitle: "정도영 댄스 공연",
      performancePeriod: "2023.12.29~2023.12.30",
      ticketPrice: 5000,
      dueDate: 2,
      genre: "DANCE",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 3,
      performanceTitle: "오늘 하는 공연",
      performancePeriod: "2023.12.28",
      ticketPrice: 5000,
      dueDate: 0,
      genre: "ETC",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 4,
      performanceTitle: "4번째 공연",
      performancePeriod: "2023.12.29~2023.12.30",
      ticketPrice: 5000,
      dueDate: 4,
      genre: "PLAY",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 5,
      performanceTitle: "다섯다섯다섯다섯다섯다섯다섯",
      performancePeriod: "2023.12.28",
      ticketPrice: 5000,
      dueDate: 3,
      genre: "DANCE",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 6,
      performanceTitle: "비트연극 정기공연",
      performancePeriod: "2023.12.29~2023.12.30",
      ticketPrice: 5000,
      dueDate: 6,
      genre: "PLAY",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 7,
      performanceTitle: "비트밴드 정기공연",
      performancePeriod: "2023.12.28",
      ticketPrice: 5000,
      dueDate: 4,
      genre: "ETC",
      posterImage: "포스터 사진 URL",
    },
    {
      performanceId: 8,
      performanceTitle: "비트연극 정기공연",
      performancePeriod: "2023.12.29~2023.12.30",
      ticketPrice: 5000,
      dueDate: 5,
      genre: "PLAY",
      posterImage: "포스터 사진 URL",
    },
  ],
};
