name: Synchronize to forked repo
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://pepperdad:${{ secrets.DEPLOY_TOKEN }}@github.com/pepperdad/BEAT-Client
          git config user.name pepperdad
          git config user.email becomegoodguy@gmail.com
      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main
      - name: Clean up
        run: |
          git remote remove forked-repo
